import enum


class PropType(enum.Enum):
    spiritGem = '晶灵石（蓝钻）'
    sorceryGem = '魔蕴石（红钻）'
    essenceContract = '魔力契约（单抽票）'
    coin = '金币'
    tinyBoost = '微型日月精华（10体力）'
    basicBoost = '初级日月精华（30体力）'
    strongBoost = '上级日月精华（100体力）'
    basicPotential = '初级潜力道具'
    intermediatePotential = '中级潜力道具'
    advancedPotential = '高级潜力道具'
    advancedUpPotential = '高级潜力道具（合成）'
    legendaryPotential = '传说潜力道具'
    smallEssenceVial = '小瓶魔力熏香（1蜜话次数）'
    middleEssenceVial = '中瓶魔力熏香（5蜜话次数）'
    bigEssenceVial = '大瓶魔力熏香（10蜜话次数）'
    expressPass = '快速通关券'
    key = '钥匙'
    basicGift = '初级礼物'
    intermediateGift = '中级礼物'
    advancedGift = '高级礼物'
    ultraGift = '回忆图画'
    holyWater_S = '小型祝福药水'
    holyWater_M = '中型祝福药水'
    holyWater_L = '大型祝福药水'
    holyWater_XL = '特大型祝福药水'
    SR_Fragment = 'SR碎片'
